name: PR Review

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  pr-review:
    if: |
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude'))

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SWE_AGENT_APP_ID }}
          private-key: ${{ secrets.SWE_AGENT_PRIVATE_KEY }}

      - name: Run Claude PR Review
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          trigger_phrase: "@claude"
          bot_id: "2152368"
          bot_name: "caa-swe-agent[bot]"
          track_progress: true
          claude_args: |
            --max-turns 50
            --model claude-sonnet-4-5-20250929
            --system-prompt "Code reviewer for Cyber-AutoAgent. Review for: PEP 8 compliance, logical code flow, no over-engineering, no emojis, minimal try/except blocks, proper error handling, security issues, test coverage >80%, type hints required. Flag: unnecessary abstractions, excessive nesting, missing edge cases. Be direct and constructive. No praise without substance."
